export interface Language {
  code: string;
  nllb: string;
  name: {
    he: string;
    en: string;
  };
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'he', nllb: 'heb_Hebr', name: { he: 'עברית', en: 'Hebrew' } },
  { code: 'en', nllb: 'eng_Latn', name: { he: 'אנגלית', en: 'English' } },
  { code: 'ru', nllb: 'rus_Cyrl', name: { he: 'רוסית', en: 'Russian' } },
  { code: 'ar', nllb: 'arb_Arab', name: { he: 'ערבית', en: 'Arabic' } },
  { code: 'es', nllb: 'spa_Latn', name: { he: 'ספרדית', en: 'Spanish' } },
  { code: 'fr', nllb: 'fra_Latn', name: { he: 'צרפתית', en: 'French' } },
  { code: 'de', nllb: 'deu_Latn', name: { he: 'גרמנית', en: 'German' } },
  { code: 'it', nllb: 'ita_Latn', name: { he: 'איטלקית', en: 'Italian' } },
  { code: 'pt', nllb: 'por_Latn', name: { he: 'פורטוגזית', en: 'Portuguese' } },
  { code: 'nl', nllb: 'nld_Latn', name: { he: 'הולנדית', en: 'Dutch' } },
  { code: 'ja', nllb: 'jpn_Jpan', name: { he: 'יפנית', en: 'Japanese' } },
  { code: 'ko', nllb: 'kor_Hang', name: { he: 'קוריאנית', en: 'Korean' } },
  { code: 'zh', nllb: 'zho_Hans', name: { he: 'סינית', en: 'Chinese' } },
  { code: 'hi', nllb: 'hin_Deva', name: { he: 'הינדית', en: 'Hindi' } },
  { code: 'tr', nllb: 'tur_Latn', name: { he: 'טורקית', en: 'Turkish' } },
  { code: 'pl', nllb: 'pol_Latn', name: { he: 'פולנית', en: 'Polish' } },
  { code: 'uk', nllb: 'ukr_Cyrl', name: { he: 'אוקראינית', en: 'Ukrainian' } },
  { code: 'vi', nllb: 'vie_Latn', name: { he: 'ויאטנמית', en: 'Vietnamese' } },
  { code: 'th', nllb: 'tha_Thai', name: { he: 'תאילנדית', en: 'Thai' } },
  { code: 'id', nllb: 'ind_Latn', name: { he: 'אינדונזית', en: 'Indonesian' } },
  { code: 'el', nllb: 'ell_Grek', name: { he: 'יוונית', en: 'Greek' } },
  { code: 'cs', nllb: 'ces_Latn', name: { he: 'צ׳כית', en: 'Czech' } },
  { code: 'sv', nllb: 'swe_Latn', name: { he: 'שוודית', en: 'Swedish' } },
  { code: 'ro', nllb: 'ron_Latn', name: { he: 'רומנית', en: 'Romanian' } },
  { code: 'hu', nllb: 'hun_Latn', name: { he: 'הונגרית', en: 'Hungarian' } },
  { code: 'da', nllb: 'dan_Latn', name: { he: 'דנית', en: 'Danish' } },
  { code: 'fi', nllb: 'fin_Latn', name: { he: 'פינית', en: 'Finnish' } },
  { code: 'no', nllb: 'nob_Latn', name: { he: 'נורווגית', en: 'Norwegian' } },
  { code: 'bn', nllb: 'ben_Beng', name: { he: 'בנגלית', en: 'Bengali' } },
  { code: 'ur', nllb: 'urd_Arab', name: { he: 'אורדו', en: 'Urdu' } },
  { code: 'fa', nllb: 'pes_Arab', name: { he: 'פרסית', en: 'Persian' } },
  { code: 'bg', nllb: 'bul_Cyrl', name: { he: 'בולגרית', en: 'Bulgarian' } },
  { code: 'ca', nllb: 'cat_Latn', name: { he: 'קטלאנית', en: 'Catalan' } },
  { code: 'hr', nllb: 'hrv_Latn', name: { he: 'קרואטית', en: 'Croatian' } },
  { code: 'sr', nllb: 'srp_Cyrl', name: { he: 'סרבית', en: 'Serbian' } },
  { code: 'sk', nllb: 'slk_Latn', name: { he: 'סלובקית', en: 'Slovak' } },
  { code: 'sl', nllb: 'slv_Latn', name: { he: 'סלובנית', en: 'Slovenian' } },
  { code: 'lt', nllb: 'lit_Latn', name: { he: 'ליטאית', en: 'Lithuanian' } },
  { code: 'lv', nllb: 'lvs_Latn', name: { he: 'לטבית', en: 'Latvian' } },
  { code: 'et', nllb: 'est_Latn', name: { he: 'אסטונית', en: 'Estonian' } },
  { code: 'ta', nllb: 'tam_Taml', name: { he: 'טמילית', en: 'Tamil' } },
  { code: 'te', nllb: 'tel_Telu', name: { he: 'טלוגו', en: 'Telugu' } },
  { code: 'ml', nllb: 'mal_Mlym', name: { he: 'מלאיאלאם', en: 'Malayalam' } },
  { code: 'mr', nllb: 'mar_Deva', name: { he: 'מראטהי', en: 'Marathi' } },
  { code: 'gu', nllb: 'guj_Gujr', name: { he: 'גוג\'ראטית', en: 'Gujarati' } },
  { code: 'tl', nllb: 'tgl_Latn', name: { he: 'טגאלוג (פיליפינית)', en: 'Tagalog (Filipino)' } },
  { code: 'sw', nllb: 'swh_Latn', name: { he: 'סוואהילי', en: 'Swahili' } },
  { code: 'af', nllb: 'afr_Latn', name: { he: 'אפריקאנס', en: 'Afrikaans' } },
  { code: 'is', nllb: 'isl_Latn', name: { he: 'איסלנדית', en: 'Icelandic' } },
  { code: 'ms', nllb: 'zsm_Latn', name: { he: 'מלאית', en: 'Malay' } },
  { code: 'ne', nllb: 'npi_Deva', name: { he: 'נפאלית', en: 'Nepali' } },
  { code: 'kk', nllb: 'kaz_Cyrl', name: { he: 'קזחית', en: 'Kazakh' } },
  { code: 'uz', nllb: 'uzn_Latn', name: { he: 'אוזבקית', en: 'Uzbek' } },
  { code: 'mk', nllb: 'mkd_Cyrl', name: { he: 'מקדונית', en: 'Macedonian' } },
  { code: 'az', nllb: 'azj_Latn', name: { he: 'אזרית', en: 'Azerbaijani' } },
  { code: 'ka', nllb: 'kat_Geor', name: { he: 'גאורגית', en: 'Georgian' } },
  { code: 'sq', nllb: 'als_Latn', name: { he: 'אלבנית', en: 'Albanian' } },
  { code: 'hy', nllb: 'hye_Armn', name: { he: 'ארמנית', en: 'Armenian' } },
  { code: 'mn', nllb: 'khk_Cyrl', name: { he: 'מונגולית', en: 'Mongolian' } },
  { code: 'bs', nllb: 'bos_Latn', name: { he: 'בוסנית', en: 'Bosnian' } }
];

export const I18N = {
  he: {
      loading: "טוען נתונים...",
      subtitle: "פענוח ותרגום חכם שרץ כולו על המחשב שלך",
      storage: "אחסון:",
      clear: "ניקוי",
      settings: "הגדרות",
      apiConnected: "API מחובר",
      setApi: "הגדר API",
      privacyTitle: "100% פרטיות - עיבוד מקומי",
      privacyDesc: "הקבצים שלך לעולם לא נשלחים לאינטרנט. כל זיהוי הקול והתרגום מתבצעים על גבי המחשב שלך בלבד (Local Processing).",
      dragTitle: "גרור קובץ וידאו או שמע לכאן",
      dragDesc: "או לחץ כאן לבחירה מהמחשב (תומך עד 2GB)",
      changeFile: "החלף קובץ",
      sourceLangLabel: "שפת הדיבור בסרטון:",
      targetLangLabel: "שפת הכתוביות (תרגום):",
      autoDetect: "זיהוי אוטומטי (Auto)",
      detectLanguageBtn: "זיהוי שפה (AI)",
      detecting: "מזהה...",
      originalLang: "שפת המקור (ללא תרגום)",
      modelSize: "גודל ואיכות המודל:",
      startProcessing: "התחל עיבוד ולמידת מכונה",
      processingWarn: "הפעולה מתבצעת באופן מקומי לחלוטין על גבי מעבד המחשב שלך. אנא אל תסגור דף זה.",
      cancelProcess: "בטל פעולה",
      progress: "התקדמות",
      readyTitle: "הכיתוביות מוכנות!",
      readyDesc: "העיבוד המקומי הסתיים בהצלחה. ניתן לערוך את הטקסט למטה לפני ההורדה.",
      copy: "העתק",
      copied: "הועתק!",
      downloadBtn: "הורד",
      editorTitle: "עורך כתוביות (ניתן לעריכה)",
      aiFeatures: "✨ פעולות AI מתקדמות (Gemini API)",
      summary: "תמצות חכם",
      grammar: "תיקון שגיאות כתיב",
      topics: "חלוקה לנושאים",
      cinematic: "התאמה קולנועית חכמה",
      startOver: "התחל מחדש עם קובץ אחר",
      errorTitle: "שגיאה בתהליך",
      tryAgain: "נסה שוב",
      adminPanel: "פאנל ניהול מנהל",
      monthlyLogins: "כניסות ייחודיות החודש:",
      sendReport: "שלח דוח חודשי",
      settingsTitle: "הגדרות מערכת",
      theme: "ערכת נושא:",
      light: "בהיר",
      dark: "כהה",
      chunks: "פיצולי הורדה מקבילית (Chunks):",
      chunksDesc: "קובע לכמה חלקים יפוצל המודל בעת ההורדה הראשונית. ערך גבוה מאיץ את ההורדה אך עלול לגרום לחסימות שרת במקרים מסוימים.",
      cpuLabel: "כוח עיבוד (ליבות מעבד):",
      cpuAuto: "אוטומטי (מומלץ)",
      cpu1: "נמוך (ליבה 1) - חסכוני בסוללה",
      cpu2: "בינוני (2 ליבות)",
      cpu4: "גבוה (4 ליבות)",
      cpu8: "מקסימלי (8 ליבות) - המהיר ביותר",
      webGpuLabel: "האצת חומרה (WebGPU - ניסיוני)",
      webGpuDesc: "משתמש בכרטיס המסך כדי להאיץ את זיהוי הקול פי 10! (נתמך בדפדפנים מודרניים)",
      subtitleSettingsTitle: "התאמה אישית של הכתוביות",
      exportFormatLabel: "פורמט הורדה (ברירת מחדל):",
      fontSizeLabel: "גודל טקסט בעורך:",
      fontSmall: "קטן",
      fontMedium: "בינוני",
      fontLarge: "גדול",
      maxCharsLabel: "אורך שורה מקסימלי (תווים):",
      maxCharsDesc: "מפצל אוטומטית כתוביות ארוכות לשורות קצרות. משפיע על פענוח של קבצים חדשים.",
      removePunctuationLabel: "הסרת סימני פיסוק (.,!?)",
      unlimited: "ללא הגבלה",
      closeSave: "סגור ושמור",
      apiTitle: "הגדרת מפתח Gemini API",
      apiDesc: "כדי להשתמש בתכונות ה-AI המתקדמות (תמצות, הגהה, עריכה יצירתית), עליך לספק מפתח API משלך. המפתח נשמר מקומית בדפדפן שלך בלבד ולא נשלח לשום שרת זר.",
      apiKeyLabel: "מפתח API:",
      apiKeyPlaceholder: "הדבק את המפתח כאן (מתחיל ב-AIza...)",
      invalidKeyFormat: "שים לב: מפתח Gemini מתחיל בדרך כלל ב-'AIza'. ייתכן שהמפתח שגוי.",
      noApiKey: "אין לך מפתח?",
      getApiKey: "לחץ כאן כדי לייצר מפתח חינמי ב-Google AI Studio",
      deleteKey: "מחק מפתח",
      cancel: "ביטול",
      keyActiveTitle: "המפתח מוגדר ופעיל",
      editKey: "ערוך מפתח",
      close: "סגור"
  },
  en: {
      loading: "Loading data...",
      subtitle: "Smart transcription & translation running entirely on your PC",
      storage: "Storage:",
      clear: "Clear",
      settings: "Settings",
      apiConnected: "API Connected",
      setApi: "Set API",
      privacyTitle: "100% Privacy - Local Processing",
      privacyDesc: "Your files never leave your computer. All speech recognition and translation are done locally.",
      dragTitle: "Drag audio or video file here",
      dragDesc: "Or click to select from your computer (Up to 2GB)",
      changeFile: "Change File",
      sourceLangLabel: "Spoken Language:",
      targetLangLabel: "Subtitle Language (Translation):",
      autoDetect: "Auto Detect",
      detectLanguageBtn: "Detect Lang (AI)",
      detecting: "Detecting...",
      originalLang: "Original Language (No Translation)",
      modelSize: "Model Size & Quality:",
      startProcessing: "Start AI Processing",
      processingWarn: "Processing locally on your computer's CPU. Please do not close this page.",
      cancelProcess: "Cancel Process",
      progress: "Progress",
      readyTitle: "Subtitles are ready!",
      readyDesc: "Local processing completed successfully. You can edit the text below before downloading.",
      copy: "Copy",
      copied: "Copied!",
      downloadBtn: "Download",
      editorTitle: "Subtitle Editor (Editable)",
      aiFeatures: "✨ Advanced AI Actions (Gemini API)",
      summary: "Smart Summary",
      grammar: "Fix Grammar",
      topics: "Extract Topics",
      cinematic: "Smart Cinematic Adaptation",
      startOver: "Start over with a different file",
      errorTitle: "Process Error",
      tryAgain: "Try Again",
      adminPanel: "Admin Panel",
      monthlyLogins: "Unique Logins this Month:",
      sendReport: "Send Monthly Report",
      settingsTitle: "System Settings",
      theme: "Theme:",
      light: "Light",
      dark: "Dark",
      chunks: "Parallel Download Chunks:",
      chunksDesc: "Determines how many parts the model is split into during initial download. Higher value speeds up download but may cause server blocks.",
      cpuLabel: "Processing Power (CPU Cores):",
      cpuAuto: "Auto (Recommended)",
      cpu1: "Low (1 Core) - Battery Saver",
      cpu2: "Medium (2 Cores)",
      cpu4: "High (4 Cores)",
      cpu8: "Max (8 Cores) - Fastest",
      webGpuLabel: "Hardware Acceleration (WebGPU - Exp)",
      webGpuDesc: "Uses GPU to speed up recognition by 10x! (Supported in modern browsers)",
      subtitleSettingsTitle: "Subtitle Customization",
      exportFormatLabel: "Default Export Format:",
      fontSizeLabel: "Editor Font Size:",
      fontSmall: "Small",
      fontMedium: "Medium",
      fontLarge: "Large",
      maxCharsLabel: "Max Characters per Line:",
      maxCharsDesc: "Automatically splits long subtitles into shorter lines. Affects new files.",
      removePunctuationLabel: "Remove Punctuation (.,!?)",
      unlimited: "Unlimited",
      closeSave: "Close & Save",
      apiTitle: "Set Gemini API Key",
      apiDesc: "To use advanced AI features (summarization, proofreading, creative adaptation), you must provide your own API key. The key is saved locally in your browser and is not sent to any external server.",
      apiKeyLabel: "API Key:",
      apiKeyPlaceholder: "Paste key here (starts with AIza...)",
      invalidKeyFormat: "Note: Gemini API keys usually start with 'AIza'. This key might be invalid.",
      noApiKey: "Don't have a key?",
      getApiKey: "Click here to generate a free key in Google AI Studio",
      deleteKey: "Delete Key",
      cancel: "Cancel",
      keyActiveTitle: "API Key is configured and active",
      editKey: "Edit Key",
      close: "Close"
  }
};
